"""tabela usuario_item

Revision ID: 6c20ee603b9b
Revises: c3e61a62d5ad
Create Date: 2026-06-07 17:03:16.336417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c20ee603b9b'
down_revision: Union[str, Sequence[str], None] = 'c3e61a62d5ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario_item',
    sa.Column('id_usuario_item', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('equipado', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('equipado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['item_loja.id_item'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id_usuario'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_usuario_item')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuario_item')
    # ### end Alembic commands ###
