"""correcao anotacao

Revision ID: f3a3cb5c4216
Revises: c6d086e0515d
Create Date: 2026-06-02 20:07:06.226152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3a3cb5c4216'
down_revision: Union[str, Sequence[str], None] = 'c6d086e0515d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('anotacao', sa.Column('titulo', sa.String(length=150), nullable=False))
    op.alter_column('anotacao', 'texto',
               type_=sa.Text(),
               nullable=True)
    op.drop_column('anotacao', 'descricao')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('anotacao', sa.Column('descricao', sa.TEXT(), autoincrement=False, nullable=True))
    op.alter_column('anotacao', 'texto',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=150),
               nullable=False)
    op.drop_column('anotacao', 'titulo')
    # ### end Alembic commands ###
