"""senha nao e obrigatoria

Revision ID: 85e7cf878c54
Revises: f0dce8957b4e
Create Date: 2026-06-20 16:34:08.934642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85e7cf878c54'
down_revision: Union[str, Sequence[str], None] = 'f0dce8957b4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usuario', 'senha_hash',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usuario', 'senha_hash',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
