"""sms em usuario

Revision ID: 8a8d7e75b223
Revises: 5693e4bb035c
Create Date: 2026-05-28 18:41:28.771810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a8d7e75b223'
down_revision: Union[str, Sequence[str], None] = '5693e4bb035c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('sms', sa.String(length=6), nullable=True))
    op.add_column('usuario', sa.Column('sms_expirado_em', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario', 'sms_expirado_em')
    op.drop_column('usuario', 'sms')
    # ### end Alembic commands ###
