"""tabela questao

Revision ID: 50056f067b37
Revises: 767a3680d4e9
Create Date: 2026-06-06 16:30:27.571885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50056f067b37'
down_revision: Union[str, Sequence[str], None] = '767a3680d4e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questao',
    sa.Column('id_questao', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('exercicio_id', sa.Integer(), nullable=False),
    sa.Column('pergunta', sa.Text(), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['exercicio_id'], ['exercicio.id_exercicio'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_questao'),
    sa.UniqueConstraint('exercicio_id', 'ordem', name='uq_questao_ordem_exercicio')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('questao')
    # ### end Alembic commands ###
