"""tabela item_loja

Revision ID: c3e61a62d5ad
Revises: 22fe251e8c26
Create Date: 2026-06-07 16:49:42.809517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3e61a62d5ad'
down_revision: Union[str, Sequence[str], None] = '22fe251e8c26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item_loja',
    sa.Column('id_item', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('preco', sa.Integer(), nullable=False),
    sa.Column('compravel_uma_vez', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.PrimaryKeyConstraint('id_item')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item_loja')
    # ### end Alembic commands ###
