"""tabela aula

Revision ID: 375b497d2d24
Revises: f3a3cb5c4216
Create Date: 2026-06-06 15:16:15.652628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '375b497d2d24'
down_revision: Union[str, Sequence[str], None] = 'f3a3cb5c4216'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aula',
    sa.Column('id_aula', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('titulo', sa.String(length=50), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('modulo', sa.Integer(), nullable=False),
    sa.Column('subtitulo_1', sa.String(length=70), nullable=False),
    sa.Column('paragrafo_1', sa.Text(), nullable=False),
    sa.Column('subtitulo_2', sa.String(length=70), nullable=True),
    sa.Column('paragrafo_2', sa.Text(), nullable=True),
    sa.Column('subtitulo_3', sa.String(length=70), nullable=True),
    sa.Column('paragrafo_3', sa.Text(), nullable=True),
    sa.Column('subtitulo_4', sa.String(length=70), nullable=True),
    sa.Column('paragrafo_4', sa.Text(), nullable=True),
    sa.Column('moeda_bonus', sa.Integer(), nullable=False),
    sa.Column('xp_bonus', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id_aula')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('aula')
    # ### end Alembic commands ###
