"""tabela usuario_exercicio

Revision ID: 22fe251e8c26
Revises: c1da4ebf65de
Create Date: 2026-06-06 18:41:09.154526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22fe251e8c26'
down_revision: Union[str, Sequence[str], None] = 'c1da4ebf65de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario_exercicio',
    sa.Column('id_usuario_exercicio', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('exercicio_id', sa.Integer(), nullable=False),
    sa.Column('iniciou', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('terminou', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('questao_atual', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('acertos', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.ForeignKeyConstraint(['exercicio_id'], ['exercicio.id_exercicio'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id_usuario'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_usuario_exercicio'),
    sa.UniqueConstraint('usuario_id', 'exercicio_id', name='uq_usuario_exercicio')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuario_exercicio')
    # ### end Alembic commands ###
