"""tabela usuario_aula

Revision ID: 6cb64dfa16c6
Revises: 375b497d2d24
Create Date: 2026-06-06 15:48:53.165075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6cb64dfa16c6'
down_revision: Union[str, Sequence[str], None] = '375b497d2d24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario_aula',
    sa.Column('id_usuario_aula', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('aula_id', sa.Integer(), nullable=False),
    sa.Column('iniciou', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('terminou', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['aula_id'], ['aula.id_aula'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id_usuario'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_usuario_aula'),
    sa.UniqueConstraint('usuario_id', 'aula_id', name='uq_usuario_aula')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuario_aula')
    # ### end Alembic commands ###
