"""tabela alternativa

Revision ID: c1da4ebf65de
Revises: 50056f067b37
Create Date: 2026-06-06 18:20:14.309087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1da4ebf65de'
down_revision: Union[str, Sequence[str], None] = '50056f067b37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alternativa',
    sa.Column('id_alternativa', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('questao_id', sa.Integer(), nullable=False),
    sa.Column('texto', sa.Text(), nullable=False),
    sa.Column('correta', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['questao_id'], ['questao.id_questao'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_alternativa')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alternativa')
    # ### end Alembic commands ###
