"""tabela usuario_ofensiva

Revision ID: 5693e4bb035c
Revises: c4c211480a11
Create Date: 2026-05-23 17:27:34.684829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5693e4bb035c'
down_revision: Union[str, Sequence[str], None] = 'c4c211480a11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario_ofensiva',
    sa.Column('id_usuario_ofensiva', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('maior_ofensiva', sa.Integer(), server_default=sa.text('1'), nullable=True),
    sa.Column('congelamentos', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('congelada_ativa', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('ultima_data_valida', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_usuario_ofensiva')
    )
    op.add_column('usuario', sa.Column('ofensiva', sa.Integer(), server_default=sa.text('0'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario', 'ofensiva')
    op.drop_table('usuario_ofensiva')
    # ### end Alembic commands ###
