"""tabela exercicio

Revision ID: 767a3680d4e9
Revises: 6cb64dfa16c6
Create Date: 2026-06-06 16:12:05.934726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '767a3680d4e9'
down_revision: Union[str, Sequence[str], None] = '6cb64dfa16c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercicio',
    sa.Column('id_exercicio', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('aula_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['aula_id'], ['aula.id_aula'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_exercicio'),
    sa.UniqueConstraint('aula_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exercicio')
    # ### end Alembic commands ###
