"""usuario oauth cascade

Revision ID: 5ee00e341283
Revises: 85e7cf878c54
Create Date: 2026-06-21 13:14:10.557091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ee00e341283'
down_revision: Union[str, Sequence[str], None] = '85e7cf878c54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('usuario_oauth_usuario_id_fkey'), 'usuario_oauth', type_='foreignkey')
    op.create_foreign_key(None, 'usuario_oauth', 'usuario', ['usuario_id'], ['id_usuario'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usuario_oauth', type_='foreignkey')
    op.create_foreign_key(op.f('usuario_oauth_usuario_id_fkey'), 'usuario_oauth', 'usuario', ['usuario_id'], ['id_usuario'])
    # ### end Alembic commands ###
