"""mitovo_banimento e equipado_em

Revision ID: f0dce8957b4e
Revises: 6c20ee603b9b
Create Date: 2026-06-07 17:08:08.558118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0dce8957b4e'
down_revision: Union[str, Sequence[str], None] = '6c20ee603b9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('motivo_banimento', sa.Text(), nullable=True))
    op.add_column('usuario_ofensiva', sa.Column('equipado_em', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario_ofensiva', 'equipado_em')
    op.drop_column('usuario', 'motivo_banimento')
    # ### end Alembic commands ###
